#服务名
spring:
  application:
    name: order-service

#服务端口
server:
  port: 5100

#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/

#feign熔断
feign:
  hystrix:
    enabled: true